### ISSUE TITLE
Feature Request: Addition of BBAE/Dspac

### ISSUE THREAD

**Issue by kdabas03** [NelsonDane/auto-rsa#204]
First of all, thanks for making/maintaining this. Would it be possible to add support for BBAE and Dspac? Im not sure how popular they are but they are next day brokers and owned by the same company. I was able to find the api for BBAE but couldn't find anything for Dspac. https://openapi.bbae.com/#/ 

The only downside for these brokers are they require a 500$ balance, otherwise they charge you a small monthly fee of $10, which can be recovered from RSA in my opinion.

Thanks again.

**Comment by NelsonDane** [comment]
Thanks for the message! I checked out the link you shared and according to BBAE support that API is not live yet, but once it is I'd be happy to add it to the project (it would be very easy since it's an official API). Until then, we have other brokers that we're working on, but I'll definitely keep an eye on BBAE/Dspace
