### ISSUE TITLE
No module named "..."

### ISSUE THREAD

**Issue by Sabermoose19** [NelsonDane/auto-rsa#278]
![image](https://github.com/NelsonDane/auto-rsa/assets/93809613/28b47108-ce31-4f4a-a65c-40090b8b24f7)

In order to try and fix my previous problem that I had with the Schwab accounts, I did a fresh install of the bot which now is giving me this error. I have ran pip install -r requirements.txt but that didn't fix the issue.

**Comment by NelsonDane** [comment]
This is very odd since we haven't used the `webdriver_manager` package for a long time. I see you're using Docker, can you make sure to get the latest version of `auto-rsa` from GitHub, then run `docker compose pull` and `docker compose up -d` to ensure you're using the newest version since that package shouldn't even be installed anymore (and it's no longer listed in `requirements.txt` or used as a dependency by any other module)

**Comment by Sabermoose19** [comment]
Fixed the issue, I removed all of my previous docker images and did a fresh install again. Fixed this issue. However, the fresh install did not fix the issue with schwab thats in the other issue.
